spring:
  application:
    name: MerchantAdmin
  profiles:
    active: dev
server:
  port: 8090

logging:
  config: classpath:logback-spring.xml

mybatis:
  mapper-locations: classpath*:/mybatis/mapper/*.xml,/mybatis/mapper/manual/*.xml
