spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/merchant?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
    username: root
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: 60000
      connection-test-query: SELECT 1
      maximum-pool-size: 500
      max-lifetime: 1800000
      minimum-idle: 50
      idle-timeout: 60000
